import { Product, Category } from './types';

export const MAIN_CATEGORIES: Category[] = [
  {
    id: 'mc1',
    name: 'Nội thất phòng khách',
    slug: 'noi-that-phong-khach',
    image: '/img/phongkhach.jpg',
    subcategories: [
      { id: 'sc1-1', name: 'Bộ sofa', slug: 'bo-sofa' },
      { id: 'sc1-2', name: 'Kệ Tivi', slug: 'ke-tivi' },
      { id: 'sc1-3', name: 'Tủ giày', slug: 'tu-giay' },
      { id: 'sc1-4', name: 'Tủ Kệ', slug: 'tu-ke' },
    ]
  },
  {
    id: 'mc2',
    name: 'Nội thất phòng ngủ',
    slug: 'noi-that-phong-ngu',
    image: '/img/phongngu.jpg',
    subcategories: [
      { id: 'sc2-1', name: 'Giường', slug: 'giuong' },
      { id: 'sc2-2', name: 'Tủ quần áo', slug: 'tu-quan-ao' },
      { id: 'sc2-3', name: 'Bàn trang điểm', slug: 'ban-trang-diem' },
    ]
  },
  {
    id: 'mc3',
    name: 'Nội thất nhà bếp',
    slug: 'noi-that-nha-bep',
    image: '/img/nhabep.jpg',
    subcategories: [
      { id: 'sc3-1', name: 'Bộ bàn ăn', slug: 'bo-ban-an' },
      { id: 'sc3-2', name: 'Tủ bếp', slug: 'tu-bep' },
    ]
  },
  {
    id: 'mc4',
    name: 'Cửa đi gỗ',
    slug: 'cua-di-go',
    image: '/img/cua.jpg',
    subcategories: []
  }
];

export const CATEGORIES: Category[] = MAIN_CATEGORIES.flatMap(mc => {
  if (!mc.subcategories || mc.subcategories.length === 0) {
    return [{
      id: mc.id,
      name: mc.name,
      slug: mc.slug,
      image: mc.image,
    }];
  }
  return mc.subcategories.map(sc => ({
    id: sc.id,
    name: sc.name,
    slug: sc.slug,
    image: mc.image,
  }));
});

export const MOCK_PRODUCTS: Product[] = [
  // Beds
  {
    id: 'p1',
    name: 'Giường ngủ gỗ công nghiệp hiện đại tiện lợi có hộc kéo',
    slug: 'giuong-ngu-go-cong-nghiep-hien-dai-tien-loi-co-hoc-keo',
    description: 'Thiết kế hiện đại tích hợp hộc kéo tiện lợi, giúp tối ưu không gian lưu trữ cho phòng ngủ của bạn.',
    longDescription: 'Giường ngủ được chế tác từ gỗ công nghiệp MDF chống ẩm cao cấp, bề mặt phủ Melamine hạn chế trầy xước và dễ dàng vệ sinh. Thiết kế tối giản, tinh tế với điểm nhấn là các hộc kéo rộng rãi tích hợp dưới gầm giường, cung cấp không gian lưu trữ chăn màn, quần áo vô cùng tiện lợi mà không làm mất đi tính thẩm mỹ. Khung giường chắc chắn, các góc cạnh được bo viền an toàn, phù hợp cho mọi không gian sống hiện đại.',
    price: 8500000,
    originalPrice: 10500000,
    images: ['/img/giuong1.jpg'],
    category: 'Giường',
    material: 'Gỗ MDF chống ẩm',
    dimensions: '1600 x 2000 mm',
    inStock: true,
    sizes: ['1600x2000', '1800x2000'],
    colors: [{name: 'Vân Gỗ Sáng', value: '#d4a373'}, {name: 'Trắng Sứ', value: '#ffffff'}],
    materials: ['Gỗ MDF phủ Melamine']
  },
  {
    id: 'p2',
    name: 'Giường gỗ gõ đỏ cổ điển Louis',
    slug: 'giuong-go-go-do-co-dien-louis',
    description: 'Chạm khắc hoa văn Louis cổ điển sang trọng, chế tác từ gỗ Gõ Đỏ nguyên khối bền bỉ.',
    longDescription: 'Giường gỗ Gõ Đỏ mang phong cách cổ điển Louis hoàng gia, với những họa tiết chạm khắc thủ công tinh xảo ở phần đầu và đuôi giường. Gỗ Gõ Đỏ quý hiếm có đặc tính cứng cáp, chịu lực tốt, vân gỗ đẹp và không bị mối mọt cong vênh. Sản phẩm đem lại sự sang trọng, quyền quý cho không gian phòng ngủ cao cấp.',
    price: 36000000,
    originalPrice: 40000000,
    images: ['/img/giuong2.jpg'],
    category: 'Giường',
    material: 'Gỗ Gõ Đỏ',
    dimensions: '1800 x 2000 mm',
    inStock: true,
    featured: true,
    sizes: ['1800x2000', '2000x2200'],
    colors: [{name: 'Gõ Đỏ Tự Nhiên', value: '#8c4b26'}],
    materials: ['Gỗ Gõ Đỏ Nam Phi']
  },
  {
    id: 'p3',
    name: 'Giường Ngủ Gỗ Tràm Nhiều Kích Thước',
    slug: 'giuong-ngu-go-tram-nhieu-kich-thuoc',
    description: 'Giường ngủ gỗ tràm tự nhiên nguyên khối, đa dạng kích thước từ 1m2 đến 2m, thiết kế tinh giản, kết cấu siêu bền bỉ mang đến giấc ngủ trọn vẹn.',
    longDescription: 'Giường ngủ được chế tác 100% từ gỗ tràm tự nhiên lâu năm, trải qua quy trình tẩm sấy công nghệ cao chống mối mọt, cong vênh triệt để. Thiết kế mang hơi hướng hiện đại, tinh giản với những đường nét vuông vức, khỏe khoắn, phù hợp với nhiều phong cách nội thất.\n\nĐặc biệt, sản phẩm có sẵn nhiều kích thước đa dạng từ 1m2 (dành cho người độc thân, phòng nhỏ) đến 2m (dành cho gia đình, không gian rộng rãi), đáp ứng hoàn hảo mọi nhu cầu sử dụng. Khung giường gia cố vạt phản chắc chắn, chịu tải trọng cao, không phát ra tiếng kêu cọt kẹt khi trở mình, đảm bảo một giấc ngủ sâu và êm ái.\n\nBề mặt gỗ được phủ sơn PU nhiều lớp giúp chống xước, chống thấm nước, đồng thời tôn lên vẻ đẹp mộc mạc của những đường vân gỗ tràm tự nhiên.',
    price: 3200000,
    originalPrice: 4000000,
    images: ['/img/giuong3.jpg'],
    category: 'Giường',
    material: 'Gỗ Tràm Tự Nhiên',
    dimensions: '1200/1400/1600/1800/2000 x 2000 mm',
    inStock: true,
    sizes: ['1200x2000', '1400x2000', '1600x2000', '1800x2000', '2000x2000'],
    sizePrices: {
      '1200x2000': 3200000,
      '1400x2000': 3500000,
      '1600x2000': 3800000,
      '1800x2000': 4200000,
      '2000x2000': 4800000
    },
    colors: [{name: 'Màu Gỗ Tự Nhiên', value: '#d4a373'}],
    materials: ['Gỗ Tràm']
  },
  {
    id: 'p4',
    name: 'Giường ngủ gỗ công nghiệp MFC hiện đại',
    slug: 'giuong-ngu-go-cong-nghiep-mfc-hien-dai',
    description: 'Giường ngủ gỗ công nghiệp MFC phong cách hiện đại, thanh lịch, mang đến không gian nghỉ ngơi thoải mái và tinh tế.',
    longDescription: 'Giường ngủ được chế tác từ gỗ công nghiệp MFC phủ Melamine cao cấp, có khả năng chống xước, chống ẩm và hạn chế mối mọt hiệu quả. Thiết kế hiện đại với những đường nét vuông vức, tinh giản, tông màu vân gỗ ấm áp giúp dễ dàng phối hợp với các món nội thất khác trong phòng ngủ. Kết cấu giường vững chắc, khả năng chịu lực tốt, đảm bảo tuổi thọ sử dụng lâu dài và mang lại giấc ngủ êm ái cho gia đình bạn.',
    price: 4500000,
    originalPrice: 5500000,
    images: ['/img/giuong4.jpg'],
    category: 'Giường',
    material: 'Gỗ công nghiệp MFC',
    dimensions: '1600 x 2000 mm',
    inStock: true,
    bestseller: true,
    sizes: ['1200x2000', '1400x2000', '1600x2000', '1800x2000'],
    sizePrices: {
      '1200x2000': 3500000,
      '1400x2000': 4000000,
      '1600x2000': 4500000,
      '1800x2000': 5000000
    },
    colors: [{name: 'Màu Vân Gỗ Sồi', value: '#dcd0c0'}, {name: 'Màu Vân Gỗ Óc Chó', value: '#5c4033'}],
    materials: ['Gỗ MFC phủ Melamine']
  },

  // Bàn Ăn
  {
    id: 'p5',
    name: 'Bộ Bàn Ăn Tròn Mâm Xoay Gỗ Tự Nhiên 6 Ghế Chạm Khắc Cổ Điển',
    slug: 'bo-ban-an-tron-mam-xoay-go-tu-nhien-6-ghe-cham-khac',
    description: 'Bộ bàn ăn tròn 6 ghế phong cách hoàng gia, mặt mâm xoay tiện lợi với các đường nét chạm khắc tinh xảo.',
    longDescription: 'Thiết kế bàn tròn mang ý nghĩa phong thủy sum vầy, kết hợp mâm xoay ở giữa giúp việc gắp thức ăn trở nên thuận tiện. Được chế tác từ gỗ tự nhiên nguyên khối cao cấp với những hoa văn đục chạm thủ công điêu luyện mang đậm nét cổ điển sang trọng, bộ bàn ăn khẳng định đẳng cấp và gu thẩm mỹ tinh tế của gia chủ. Ghế ngồi được bọc nệm êm ái, lưng tựa thiết kế ôm sát cơ thể mang lại sự thoải mái tối đa.',
    price: 45000000,
    originalPrice: 52000000,
    images: ['/img/bobanan1.jpg'],
    category: 'Bộ bàn ăn',
    material: 'Gỗ Hương Đá Tự Nhiên',
    dimensions: 'Đường kính 1300mm x Cao 750mm',
    inStock: true,
    featured: true,
    sizes: ['Đường kính 1300mm (6 ghế)', 'Đường kính 1500mm (8 ghế)'],
    colors: [{name: 'Màu Gỗ Cổ Điển', value: '#592915'}],
    materials: ['Gỗ Hương Đá', 'Gỗ Gõ Đỏ']
  },
  {
    id: 'p6',
    name: 'Bộ Bàn Ăn Chữ Nhật 6 Ghế Nan',
    slug: 'bo-ban-an-chu-nhat-6-ghe-nan',
    description: 'Bộ bàn ăn hình chữ nhật với 6 ghế nan lưng dọc thanh lịch, phù hợp cho gia đình từ 4-6 người.',
    longDescription: 'Sở hữu thiết kế hình chữ nhật tối giản và hiện đại, bộ bàn ăn dễ dàng hòa hợp với nhiều không gian nội thất phòng ăn khác nhau. Điểm nhấn là 6 chiếc ghế với thiết kế lưng nan sọc (spindle) thanh thoát, tựa lưng vát nhẹ giúp người ngồi luôn cảm thấy thoải mái trong suốt bữa ăn. Chất liệu gỗ sồi tự nhiên màu sáng mang đến cảm giác rộng rãi và trẻ trung cho căn bếp.',
    price: 12500000,
    originalPrice: 14000000,
    images: ['/img/bobanan2.jpg'],
    category: 'Bộ bàn ăn',
    material: 'Gỗ Sồi Tự Nhiên',
    dimensions: '1600 x 800 x 750 mm',
    inStock: true,
    bestseller: true,
    sizes: ['1600x800x750mm (6 ghế)'],
    colors: [{name: 'Màu Sồi Sáng', value: '#deba93'}],
    materials: ['Gỗ Sồi Tự Nhiên', 'Gỗ Cao Su']
  },
  {
    id: 'p7',
    name: 'Bộ Bàn Ăn Tròn Mâm Xoay Gỗ Sồi Tự Nhiên 6 Ghế Màu Sáng Hiện Đại',
    slug: 'bo-ban-an-tron-mam-xoay-go-soi-tu-nhien-mau-sang',
    description: 'Bàn ăn tròn hiện đại màu gỗ sồi sáng kết hợp mâm xoay thông minh, mang đến không gian phòng ăn thanh lịch.',
    longDescription: 'Với màu sắc vàng sáng tự nhiên đặc trưng của gỗ sồi Nga, bộ bàn ăn tròn mâm xoay thổi một luồng gió tươi mới và trẻ trung vào không gian bếp. Mâm xoay kính cường lực êm ái tích hợp trên mặt bàn hỗ trợ tối đa việc chia sẻ thức ăn trong những bữa tiệc gia đình. Ghế ăn thiết kế chắc chắn với phần tựa lưng uốn cong mềm mại, mặt ngồi bọc nệm simili cao cấp chống thấm nước giúp vệ sinh dễ dàng.',
    price: 18500000,
    originalPrice: 21000000,
    images: ['/img/bobanan3.jpg'],
    category: 'Bộ bàn ăn',
    material: 'Gỗ Sồi Nga',
    dimensions: 'Đường kính 1200mm',
    inStock: true,
    sizes: ['Đường kính 1200mm (6 ghế)'],
    colors: [{name: 'Gỗ Sồi Sáng', value: '#d4a373'}],
    materials: ['Gỗ Sồi Nga', 'Nệm Simili']
  },

  // Sofa
  {
    id: 'p8',
    name: 'Bộ Sofa Gỗ Tự Nhiên Góc L Hiện Đại Kèm Nệm Bọc Da Cao Cấp',
    slug: 'bo-sofa-go-tu-nhien-goc-l-hien-dai',
    description: 'Thiết kế góc L tối ưu không gian, kết hợp giữa khung gỗ tự nhiên vững chắc và nệm bọc da cao cấp êm ái.',
    longDescription: 'Bộ sofa góc chữ L mang phong cách hiện đại là sự lựa chọn hoàn hảo cho phòng khách chung cư hay nhà phố. Khung ghế được làm từ gỗ tự nhiên đã qua xử lý chống mối mọt, cong vênh, đem lại độ bền vượt trội. Nệm ngồi và tựa lưng sử dụng mút xốp mật độ cao, bọc da công nghiệp cao cấp mềm mại, dễ dàng vệ sinh. Thiết kế góc chữ L giúp tận dụng tối đa diện tích phòng, mang đến không gian sinh hoạt chung rộng rãi và sang trọng.',
    price: 32000000,
    originalPrice: 38000000,
    images: ['/img/bosofa1.jpg'],
    category: 'Bộ sofa',
    material: 'Gỗ Tự Nhiên, Da Công Nghiệp',
    dimensions: '2800 x 1800 x 850 mm',
    inStock: true,
    featured: true,
    sizes: ['2400x1600mm', '2800x1800mm', '3200x2000mm'],
    colors: [{name: 'Màu Gỗ Tự Nhiên - Da Bò', value: '#8b4513'}, {name: 'Màu Óc Chó - Da Đen', value: '#1a1a1a'}],
    materials: ['Gỗ Sồi + Da PU', 'Gỗ Cao Su + Da Microfiber']
  },
  {
    id: 'p9',
    name: 'Bộ Bàn Ghế Salon Gỗ Tự Nhiên Chạm Khắc Cổ Điển Sang Trọng',
    slug: 'bo-ban-ghe-salon-go-tu-nhien-cham-khac',
    description: 'Bộ salon gỗ cao cấp với những đường nét chạm khắc thủ công tinh xảo, thể hiện đẳng cấp và gu thẩm mỹ của gia chủ.',
    longDescription: 'Mang đậm phong cách cổ điển truyền thống, bộ bàn ghế salon được chế tác hoàn toàn từ 100% gỗ tự nhiên quý hiếm (Gõ đỏ/Hương đá). Dưới bàn tay tài hoa của các nghệ nhân lành nghề, từng chi tiết hoa văn uốn lượn được đục chạm thủ công tỉ mỉ, sắc nét. Bộ sản phẩm không chỉ là món đồ nội thất bền bỉ vượt thời gian mà còn mang ý nghĩa phong thủy tốt lành, đem lại sự thịnh vượng, quyền quý cho không gian phòng khách.',
    price: 85000000,
    originalPrice: 95000000,
    images: ['/img/bosofa2.jpg'],
    category: 'Bộ sofa',
    material: 'Gỗ Gõ Đỏ / Gỗ Hương Đá',
    dimensions: 'Đoản dài: 2200mm, Ghế đơn: 950mm',
    inStock: true,
    bestseller: true,
    sizes: ['Bộ 6 món', 'Bộ 8 món', 'Bộ 10 món'],
    colors: [{name: 'Màu Gỗ Tự Nhiên', value: '#8c4b26'}, {name: 'Màu Cánh Gián', value: '#5e2117'}],
    materials: ['Gỗ Gõ Đỏ Nam Phi', 'Gỗ Hương Đá Nam Phi']
  },
  {
    id: 'p10',
    name: 'Bộ Bàn Ghế Sofa Gỗ Khung Nan Thoáng Kèm Bàn Trà & Bàn Kẹp',
    slug: 'bo-ban-ghe-sofa-go-khung-nan',
    description: 'Sofa mộc mạc với thiết kế khung nan sọc dọc ấn tượng, mang lại cảm giác thoáng đãng và gần gũi với thiên nhiên.',
    longDescription: 'Bộ sofa gỗ thiết kế khung nan dọc (spindle) mang phong cách Japandi thanh lịch và mộc mạc. Các thanh gỗ tròn được tiện gọt đồng đều, xếp song song tạo thành phần tựa lưng thông thoáng, tinh tế. Trọn bộ bao gồm ghế băng dài, ghế đơn, bàn trà mặt gỗ và bàn kẹp tiện dụng, đáp ứng trọn vẹn nhu cầu tiếp khách. Chất liệu gỗ tự nhiên tông màu sáng ấm áp mang lại sự tươi mới, nhẹ nhàng cho ngôi nhà của bạn.',
    price: 18500000,
    images: ['/img/bosofa3.jpg'],
    category: 'Bộ sofa',
    material: 'Gỗ Sồi Tự Nhiên, Đệm Nỉ',
    dimensions: 'Văng dài: 2000mm, Ghế đơn: 850mm',
    inStock: true,
    sizes: ['Bộ tiêu chuẩn (1 văng, 2 ghế đơn, 1 bàn trà, 1 bàn kẹp)'],
    colors: [{name: 'Gỗ Sồi Sáng', value: '#d4a373'}],
    materials: ['Gỗ Sồi + Nệm Nỉ Thô', 'Gỗ Cao Su + Nệm Linen']
  },

  // Tủ Quần Áo
  {
    id: 'p11',
    name: 'Tủ quần áo bốn cánh gỗ sồi hiện đại',
    slug: 'tu-quan-ao-bon-canh-go-soi-hien-dai',
    description: 'Tủ quần áo gỗ sồi tự nhiên bốn cánh phong cách hiện đại, thanh lịch, cung cấp không gian lưu trữ rộng rãi cho cả gia đình.',
    longDescription: 'Được chế tác từ gỗ sồi Nga tự nhiên nhập khẩu, tủ quần áo bốn cánh mang phong cách hiện đại với thiết kế tinh giản, hạn chế các chi tiết cầu kỳ để tôn lên đường vân gỗ tự nhiên tuyệt đẹp.\n\nTủ được chia làm nhiều ngăn với chức năng đa dạng, bao gồm ngăn treo quần áo dài, ngăn quần áo gấp và các hộc kéo tiện dụng, đáp ứng tối đa nhu cầu lưu trữ. Gỗ sồi đã qua quá trình tẩm sấy công nghệ cao đảm bảo chống cong vênh, mối mọt, kết hợp cùng lớp sơn PU cao cấp bảo vệ bề mặt và giữ màu gỗ luôn bền đẹp.',
    price: 16500000,
    originalPrice: 19500000,
    images: ['/img/tuquanao1.jpg'],
    category: 'Tủ quần áo',
    material: 'Gỗ sồi Nga',
    dimensions: '2000 x 2200 x 600 mm',
    inStock: true,
    sizes: ['2000 x 2200 x 600 mm', '2200 x 2400 x 600 mm'],
    colors: [{name: 'Màu Gỗ Sồi Tự Nhiên', value: '#d4a373'}],
    materials: ['Gỗ Sồi Tự Nhiên']
  },
  {
    id: 'p12',
    name: 'Tủ quần áo gỗ hương bốn cánh có kệ trang trí',
    slug: 'tu-quan-ao-go-huong-bon-canh-co-ke-trang-tri',
    description: 'Tủ quần áo cao cấp chế tác từ gỗ hương quý hiếm, kết hợp kệ trang trí tiện dụng ở góc tủ.',
    longDescription: 'Tủ quần áo bốn cánh rộng rãi được làm từ chất liệu gỗ hương tự nhiên quý hiếm, mang đến vẻ đẹp sang trọng và đẳng cấp cho phòng ngủ. Tủ nổi bật với vân gỗ hương đỏ đặc trưng và hương thơm tự nhiên nhẹ nhàng, chống mối mọt vĩnh viễn.\n\nThiết kế thông minh với một bên tích hợp hệ kệ trang trí bo tròn các góc, không chỉ an toàn mà còn là không gian lý tưởng để trưng bày đồ lưu niệm, túi xách hay đồ trang trí. Các ngăn chứa đồ bên trong được bố trí khoa học với phụ kiện bản lề giảm chấn, giúp thao tác đóng mở nhẹ nhàng êm ái.',
    price: 28000000,
    originalPrice: 32000000,
    images: ['/img/tuquanao2.jpg'],
    category: 'Tủ quần áo',
    material: 'Gỗ Hương Đá',
    dimensions: '2400 x 2400 x 600 mm',
    inStock: true,
    sizes: ['2400 x 2400 x 600 mm', '2600 x 2400 x 600 mm'],
    colors: [{name: 'Gỗ Hương Đỏ', value: '#8c4b26'}],
    materials: ['Gỗ Hương Đá Tự Nhiên']
  },

  // Kệ Tivi
  {
    id: 'p13',
    name: 'Kệ Tivi Gỗ Tự Nhiên Màu Óc Chó Phối Cánh Kính Sang Trọng',
    slug: 'ke-tivi-go-tu-nhien-mau-oc-cho-phoi-canh-kinh',
    description: 'Kệ tivi gỗ tự nhiên sang trọng màu óc chó trầm ấm, kết hợp cánh kính thanh lịch tôn lên vẻ đẹp phòng khách.',
    longDescription: 'Mang đến không gian đẳng cấp với chiếc kệ tivi được chế tác từ gỗ tự nhiên chất lượng cao, sơn màu óc chó nâu trầm quyến rũ. Điểm nhấn nổi bật là phần cánh tủ bằng kính cường lực màu trà sang trọng, giúp bạn dễ dàng trưng bày các thiết bị điện tử hoặc đồ decor. Các ngăn kéo rộng rãi sử dụng ray trượt giảm chấn êm ái, tối ưu không gian lưu trữ và đem lại trải nghiệm mượt mà khi sử dụng.',
    price: 6500000,
    originalPrice: 7800000,
    images: ['/img/ketivi1.jpg'],
    category: 'Kệ Tivi',
    material: 'Gỗ Tự Nhiên Cao Cấp',
    dimensions: '2000 x 400 x 550 mm',
    inStock: true,
    bestseller: true,
    sizes: ['1600mm', '1800mm', '2000mm', '2200mm'],
    colors: [{name: 'Màu Óc Chó', value: '#3c2415'}],
    materials: ['Gỗ Sồi sơn Óc Chó', 'Gỗ Cao Su sơn Óc Chó']
  },
  {
    id: 'p14',
    name: 'Kệ Tivi Gỗ Sồi Tự Nhiên Màu Sáng Thiết Kế 2 Tầng 4 Ngăn Kéo',
    slug: 'ke-tivi-go-soi-tu-nhien-mau-sang-thiet-ke-2-tang',
    description: 'Thiết kế 2 tầng thông minh cùng 4 ngăn kéo rộng rãi, kệ tivi gỗ sồi mang đến nét trẻ trung, hiện đại cho ngôi nhà.',
    longDescription: 'Kệ tivi gỗ sồi Nga tự nhiên mang vẻ đẹp thanh lịch với tông màu vàng nhạt và những đường vân gỗ uốn lượn đặc trưng. Thiết kế 2 tầng cung cấp không gian lý tưởng cho các thiết bị âm thanh, máy chơi game hoặc sách báo. Bốn ngăn kéo lớn đối xứng hai bên giúp phân loại và cất giữ đồ đạc gọn gàng. Kết cấu khung chân chắc chắn, khoảng sáng gầm vừa đủ giúp việc vệ sinh sàn nhà trở nên dễ dàng hơn bao giờ hết.',
    price: 5800000,
    images: ['/img/ketivi2.jpg'],
    category: 'Kệ Tivi',
    material: 'Gỗ Sồi Nga Tự Nhiên',
    dimensions: '1800 x 400 x 500 mm',
    inStock: true,
    featured: true,
    sizes: ['1600mm', '1800mm', '2000mm'],
    colors: [{name: 'Màu Sồi Tự Nhiên', value: '#d4a373'}],
    materials: ['Gỗ Sồi Nga']
  },
  {
    id: 'p15',
    name: 'Kệ Tivi Gỗ Tự Nhiên Bo Góc Chân Quỳ Vân Gỗ Chọn Lọc Cao Cấp',
    slug: 'ke-tivi-go-tu-nhien-bo-goc-chan-quy',
    description: 'Sự kết hợp hoàn hảo giữa nét truyền thống và hiện đại với kệ tivi chân quỳ bo góc mềm mại, an toàn.',
    longDescription: 'Tôn vinh vẻ đẹp mộc mạc qua từng đường vân gỗ được tuyển chọn kỹ lưỡng, chiếc kệ tivi này nổi bật với thiết kế cạnh tủ được bo tròn tỉ mỉ, không chỉ tạo sự mềm mại trong thị giác mà còn đảm bảo an toàn tuyệt đối cho gia đình có trẻ nhỏ. Phần chân đế kiểu dáng "chân quỳ" truyền thống nhưng được cách điệu tinh tế, mang lại sự vững chãi và nét thẩm mỹ Á Đông độc đáo, phù hợp với nhiều phong cách nội thất đa dạng.',
    price: 7200000,
    originalPrice: 8500000,
    images: ['/img/ketivi3.jpg'],
    category: 'Kệ Tivi',
    material: 'Gỗ Tự Nhiên Tuyển Chọn',
    dimensions: '2200 x 420 x 450 mm',
    inStock: true,
    sizes: ['1800mm', '2000mm', '2200mm', '2400mm'],
    colors: [{name: 'Vân Gỗ Đẹp', value: '#8c4b26'}, {name: 'Màu Cánh Gián', value: '#5e2117'}],
    materials: ['Gỗ Gõ Đỏ', 'Gỗ Hương Đá']
  },

  // Tủ Giày
  {
    id: 'p16',
    name: 'Tủ Giày Gỗ Tự Nhiên 3 Cánh Phủ Bóng Cao Cấp Kiểu Dáng Hiện Đại',
    slug: 'tu-giay-go-tu-nhien-3-canh-phu-bong-cao-cap',
    description: 'Tủ giày gỗ tự nhiên 3 cánh thiết kế hiện đại, bề mặt phủ bóng sang trọng, không gian chứa giày rộng rãi.',
    longDescription: 'Tủ giày được chế tác từ gỗ tự nhiên chất lượng, bề mặt phủ lớp sơn bóng cao cấp chống trầy xước và dễ lau chùi. Thiết kế 3 cánh mở kiểu dáng hiện đại tối ưu sức chứa, các đợt kệ bên trong sắp xếp khoa học giúp phân loại và bảo quản giày dép gọn gàng, tránh bụi bẩn. Thiết kế đơn giản nhưng sang trọng thích hợp cho mọi không gian nội thất.',
    price: 3600000,
    originalPrice: 4200000,
    images: ['/img/tugiay1.jpg'],
    category: 'Tủ giày',
    material: 'Gỗ Tự Nhiên Cao Cấp',
    dimensions: '1200 x 350 x 1000 mm',
    inStock: true,
    bestseller: true,
    sizes: ['1200x350x1000mm', '1400x350x1000mm'],
    colors: [{name: 'Màu cánh gián', value: '#6a361e'}, {name: 'Màu gỗ tự nhiên', value: '#cdb492'}],
    materials: ['Gỗ Tự Nhiên Sơn PU']
  },
  {
    id: 'p17',
    name: 'Tủ Giày Gỗ Tự Nhiên 4 Cánh Họa Tiết Quả Trám Kèm 3 Ngăn Kéo',
    slug: 'tu-giay-go-tu-nhien-4-canh-hoa-tiet-qua-tram',
    description: 'Tủ giày gỗ tự nhiên 4 cánh họa tiết quả trám cổ điển kết hợp 3 ngăn kéo phụ trợ tiện dụng.',
    longDescription: 'Sản phẩm tủ giày mang phong cách tân cổ điển với cánh tủ chạm khắc họa tiết quả trám tinh xảo trên nền gỗ tự nhiên vân đẹp mắt. Thiết kế 4 cánh lớn mang lại sức chứa khủng, đáp ứng nhu cầu sử dụng của đại gia đình. Kèm theo đó là 3 ngăn kéo phía trên tiện lợi để cất giữ chìa khóa, áo mưa, xi đánh giày hay các vật dụng nhỏ gọn khác, giúp không gian sảnh thêm phần gọn gàng, ngăn nắp.',
    price: 5200000,
    images: ['/img/tugiay2.jpg'],
    category: 'Tủ giày',
    material: 'Gỗ Tự Nhiên Nguyên Khối',
    dimensions: '1600 x 350 x 1100 mm',
    inStock: true,
    sizes: ['1600x350x1100mm'],
    colors: [{name: 'Màu Nâu Óc Chó', value: '#4b3621'}, {name: 'Màu Gỗ Tự Nhiên', value: '#c7a38b'}],
    materials: ['Gỗ Sồi Nga', 'Gỗ Xoan Đào']
  },
  {
    id: 'p18',
    name: 'Tủ Giày Gỗ Tự Nhiên 3 Cánh Chớp Thoáng Khí Khử Mùi Kèm Ngăn Kéo',
    slug: 'tu-giay-go-tu-nhien-3-canh-chop-thoang-khi-kem-ngan-keo',
    description: 'Thiết kế cánh chớp (louver) thông minh giúp đối lưu không khí, kết hợp ngăn kéo tiện dụng cho gia đình hiện đại.',
    longDescription: 'Tủ giày 3 cánh làm từ gỗ tự nhiên sở hữu thiết kế cánh chớp độc đáo, hỗ trợ thông gió tối đa giúp giày dép luôn khô ráo và không bị ám mùi khó chịu, ngăn chặn vi khuẩn nấm mốc phát triển. Ngoài ra, tủ còn được tích hợp thêm các ngăn kéo phía trên tiện ích, dễ dàng lưu trữ các đồ dùng nhỏ nhặt hằng ngày ở lối ra vào. Kết cấu khung gỗ bền bỉ cùng tông màu ấm áp mang lại sự thân thiện cho không gian sống.',
    price: 4800000,
    originalPrice: 5500000,
    images: ['/img/tugiay3.jpg'],
    category: 'Tủ giày',
    material: 'Gỗ Tự Nhiên Đã Xử Lý',
    dimensions: '1200 x 350 x 1000 mm',
    inStock: true,
    featured: true,
    sizes: ['1200x350x1000mm'],
    colors: [{name: 'Màu Gỗ Tự Nhiên', value: '#d4a373'}],
    materials: ['Gỗ Cao Su Tự Nhiên', 'Gỗ Thông Ghép']
  },

  // Bonus
  {
    id: 'p19',
    name: 'Tủ Trưng Bày Đứng Phong Cách Hiện Đại Phối Màu Trắng - Gỗ Sồi (Có Cửa Kính & Kệ Mở)',
    slug: 'tu-trung-bay-dung-phong-cach-hien-dai-phoi-mau-trang-go-soi',
    description: 'Tủ trưng bày đứng phong cách hiện đại phối màu trắng - gỗ sồi, tích hợp cửa kính và hệ kệ mở đa năng.',
    longDescription: 'Thiết kế hiện đại mang đến giải pháp lưu trữ hoàn hảo với hệ tủ kính kết hợp kệ mở thông minh. Sự pha trộn tinh tế giữa màu trắng sứ thanh lịch và họa tiết vân gỗ sồi tự nhiên tạo nên điểm nhấn nhẹ nhàng cho không gian phòng khách, phòng làm việc hay thư viện. Các đợt kệ chắc chắn có thể điều chỉnh độ cao để trưng bày bộ sưu tập, sách hay đồ decor một cách khoa học.',
    price: 4200000,
    originalPrice: 5000000,
    images: ['/img/ketrangtri1.jpg'],
    category: 'Tủ Kệ',
    material: 'Gỗ MDF chống ẩm phủ Melamine',
    dimensions: '800 x 400 x 2000 mm',
    inStock: true,
    sizes: ['800 x 400 x 2000 mm'],
    colors: [{name: 'Trắng - Gỗ Sồi', value: '#d4a373'}],
    materials: ['Gỗ MDF Melamine']
  },
  {
    id: 'p20',
    name: 'Kệ Vách Ngăn Phòng Trang Trí Chân Kim Loại Màu Gỗ Sồi Sáng',
    slug: 'ke-vach-ngan-phong-trang-tri-chan-kim-loai-mau-go-soi-sang',
    description: 'Kệ vách ngăn trang trí đa năng chân kim loại kết hợp đợt gỗ sồi sáng, phân chia không gian mở tinh tế.',
    longDescription: 'Chiếc kệ vách ngăn được thiết kế theo xu hướng hiện đại, sử dụng khung chân kim loại sơn tĩnh điện cứng cáp kết hợp với những đợt kệ gỗ công nghiệp màu sồi sáng ấm áp. Sản phẩm không chỉ cung cấp không gian trưng bày đồ vật lưu niệm, sách, chậu cây nhỏ mà còn đóng vai trò như một vách ngăn phân chia các khu vực một cách tinh tế mà vẫn giữ được sự thông thoáng, ánh sáng tự nhiên cho toàn bộ căn phòng.',
    price: 3800000,
    images: ['/img/ketrangtri2.jpg'],
    category: 'Tủ Kệ', 
    material: 'Khung sắt sơn tĩnh điện, Gỗ MDF',
    dimensions: '1200 x 300 x 2000 mm',
    inStock: true,
    featured: true,
    sizes: ['1200x300x2000 mm'],
    colors: [{name: 'Khung Đen - Gỗ Sồi Sáng', value: '#dcd0c0'}],
    materials: ['Khung kim loại', 'Gỗ công nghiệp']
  },
  {
    id: 'p21',
    name: 'Bàn Trang Điểm Hiện Đại Đèn LED',
    slug: 'ban-trang-diem-hien-dai-den-led',
    description: 'Thiết kế thanh lịch, tích hợp gương đèn LED thông minh.',
    longDescription: 'Bàn trang điểm gỗ MDF chống ẩm phủ Melamine cao cấp, trang bị gương tròn với đèn LED cảm ứng 3 chế độ sáng giúp bạn makeup hoàn hảo trong mọi điều kiện. Ngăn kéo rộng rãi chia ô lưu trữ đồ trang điểm tiện lợi.',
    price: 3500000,
    images: ['/img/bantrangdiem1.jpg'],
    category: 'Bàn trang điểm',
    material: 'Gỗ MDF phủ Melamine',
    dimensions: '1000 x 400 x 1350 mm',
    inStock: true,
    sizes: ['80cm', '100cm', '120cm'],
    colors: [{name: 'Trắng Sứ', value: '#ffffff'}, {name: 'Xám Ghi', value: '#808080'}],
    materials: ['Gỗ MDF']
  },
  {
    id: 'p22',
    name: 'Hệ Tủ Bếp Gỗ Cao Cấp Thiết Kế Cửa Chớp Độc Đáo',
    slug: 'he-tu-bep-go-cao-cap-thiet-ke-cua-chop',
    description: 'Hệ tủ bếp thiết kế cửa chớp thông thoáng, làm từ gỗ tự nhiên cao cấp mang nét đẹp tinh tế và cổ điển.',
    longDescription: 'Được chế tác từ gỗ tự nhiên chất lượng cao qua tẩm sấy kỹ lưỡng, hệ tủ bếp gây ấn tượng với thiết kế cánh cửa chớp (louver) tinh xảo. Kiểu dáng cánh chớp không chỉ tạo nét thẩm mỹ độc đáo pha trộn giữa truyền thống và hiện đại mà còn giúp khoang tủ luôn thông thoáng, tránh ẩm mốc. Tủ tích hợp các phụ kiện thông minh giúp công việc bếp núc trở nên tiện nghi và dễ dàng hơn.',
    price: 35000000,
    images: ['/img/tubep.jpg'],
    category: 'Tủ bếp',
    material: 'Gỗ Tự Nhiên',
    dimensions: 'Thiết kế theo yêu cầu',
    inStock: true,
    featured: true,
    sizes: ['Thiết kế theo yêu cầu'],
    colors: [{name: 'Màu Gỗ Tự Nhiên', value: '#d4a373'}, {name: 'Màu Trắng Sứ', value: '#ffffff'}],
    materials: ['Gỗ Sồi tự nhiên', 'Gỗ Cao su tự nhiên']
  },
  {
    id: 'p23',
    name: 'Cửa Gỗ Tự Nhiên 4 Cánh Mặt Tiền Chạm Khắc Họa Tiết Tròn Kèm Ô Trán',
    slug: 'cua-go-tu-nhien-4-canh-mat-tien-cham-khac',
    description: 'Cửa chính 4 cánh gỗ tự nhiên cao cấp với họa tiết chạm khắc hình tròn độc đáo và ô trán sang trọng.',
    longDescription: 'Sản phẩm cửa chính 4 cánh mặt tiền được làm từ gỗ tự nhiên nguyên khối cao cấp, đã qua quy trình xử lý chống cong vênh và mối mọt. Điểm nhấn nổi bật của bộ cửa là những họa tiết chạm khắc hình tròn đồng tâm tinh xảo trên bề mặt cánh, mang ý nghĩa viên mãn và thu hút tài lộc. Kết hợp cùng phần ô trán cửa rộng lớn phía trên giúp đón ánh sáng tự nhiên, mang đến vẻ đẹp bề thế, uy nghi cho mặt tiền ngôi nhà.',
    price: 32500000,
    originalPrice: 35000000,
    images: ['/img/cua1.jpg'],
    category: 'Cửa đi gỗ',
    material: 'Gỗ Tự Nhiên Nguyên Khối',
    dimensions: 'Thiết kế theo bản vẽ',
    inStock: true,
    featured: true,
    sizes: ['Thiết kế đo ni đóng giày'],
    colors: [{name: 'Màu Gỗ Tự Nhiên', value: '#d4a373'}, {name: 'Màu Cánh Gián', value: '#804000'}],
    materials: ['Gỗ Gõ Đỏ', 'Gỗ Lim Nam Phi']
  },
  {
    id: 'p24',
    name: 'Cửa Chính Gỗ Tự Nhiên Vòm Cao Tân Cổ Điển Kèm Trán Cửa Hoành Tráng',
    slug: 'cua-chinh-go-tu-nhien-vom-cao-tan-co-dien',
    description: 'Cửa gỗ tự nhiên thiết kế vòm cong tân cổ điển, nổi bật với phần trán cửa hoành tráng và đường phào chỉ tinh tế.',
    longDescription: 'Bộ cửa chính mang đậm phong cách kiến trúc tân cổ điển Châu Âu với thiết kế vòm cong mềm mại và sang trọng. Chế tác từ chất liệu gỗ tự nhiên quý hiếm, cửa được chăm chút tỉ mỉ qua những đường phào chỉ phay sâu sắc nét. Phần trán cửa được thiết kế hoành tráng, bề thế kết hợp cùng cấu trúc cánh vững chãi không chỉ đảm bảo an ninh tuyệt đối mà còn khẳng định đẳng cấp, sự thịnh vượng của gia chủ.',
    price: 45000000,
    images: ['/img/cua2.jpg'],
    category: 'Cửa đi gỗ',
    material: 'Gỗ Tự Nhiên Cao Cấp',
    dimensions: 'Thiết kế theo yêu cầu',
    inStock: true,
    sizes: ['Thiết kế theo yêu cầu'],
    colors: [{name: 'Màu Gỗ Óc Chó', value: '#4a2c11'}, {name: 'Màu Nâu Đỏ', value: '#591e06'}],
    materials: ['Gỗ Óc Chó', 'Gỗ Hương Đá']
  }
];
